name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flask_sqlalchemy
        pip install werkzeug
        # Add other dependencies here

    - name: Run Tests
      run: |
        python -m unittest discover -s . -p '*_test.py'
